INSERT INTO USUARIOS (NOME, SENHA, EMAIL, ID) VALUES ('Felipe de Almeida Gomes', '123', 'falmeidagomes13@gmail.com', DEFAULT);
INSERT INTO USUARIOS (NOME, SENHA, EMAIL, ID) VALUES ('Ketlin Pecharka Nunes', '321', 'kpecharka@gmail.com', DEFAULT);

INSERT INTO CATEGORIAS (DESCRICAO, USUARIO_ID, ID) VALUES ('Salgado', 1, DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, USUARIO_ID, ID) VALUES ('Doce', 1, DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, USUARIO_ID, ID) VALUES ('Delícia', 1, DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, USUARIO_ID, ID) VALUES ('Dia-a-dia', 1, DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, USUARIO_ID, ID) VALUES ('Picante', 1, DEFAULT);

INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Leite', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Óleo', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Sal', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Polvilho Doce', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Queijo Ralado', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Ovo', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Açucar', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Milho', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Ervilha', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Azeite', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Farinha de Trigo', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Fermento Biológico', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Água', 1, DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, USUARIO_ID, ID) VALUES ('Pinga', 1, DEFAULT);

INSERT INTO RECEITAS (PREPARACAO_MINUTO, ID, USUARIO_ID, OBS_LIVRE, DESCRICAO) VALUES (25, DEFAULT, 1, 'A clássica receita de pão de queijo com polvilho doce amada pelos brasileiros! Descubra como fazer aquela massa fofinha e arrase no preparo do seu pão de queijo caseiro!', 'Pão de Queijo');

INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (2, 1);
INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (3, 1);

INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (1, 1, '2 copos americanos de leite');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (13, 1, '1 copo americano de água');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (2, 1, '1/3 de copo americano de óleo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (3, 1, '1 colher de sopa de sal');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (4, 1, '500 g de polvilho doce');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (5, 1, 'Queijo ralado a gosto');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (6, 1, '3 ovos inteiros');

INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Ferva o leite com a água e o óleo.', 1);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Em uma vasilha misture o polvilho e o sal.', 2);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Jogue o liquido fervido e misture com uma colher grande.', 3);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Espere esfriar e despeje o queijo ralado e os ovos.', 4);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Misture a massa com a mão amassando bem até virar uma cola caseira dura.', 5);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Faça bolinhas do tamanho que preferir.', 6);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Asse em forno bem quente até dourar.', 7);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 1, 'Sirva quentinho.', 8);


INSERT INTO RECEITAS (PREPARACAO_MINUTO, ID, USUARIO_ID, OBS_LIVRE, DESCRICAO) VALUES (15, DEFAULT, 1, 'Delicinha de pizza', 'Massa de pizza');

INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (2, 2);
INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (4, 2);

INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (11, 2, '1 kg de farinha de trigo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (12, 2, '30 g de fermento biológico');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (13, 2, '3 xícaras de água morna');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (2, 2, '3/4 xícaras de óleo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (3, 2, '1 colher (chá) de sal');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (7, 2, '1 colher (chá) de açúcar');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (14, 2, '1 colher (sopa) de pinga');

INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Misture o fermento, o sal e o açúcar em um pouco de água morna, até que o fermento esteja completamente dissolvido.', 1);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Em seguida, adicione metade da medida de farinha de trigo, o óleo e mexa até criar uma consistência pastosa.', 2);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Acrescente o restante da farinha de trigo, a pinga, a água morna e misture bem.', 3);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Assim que a massa desgrudar das mãos, deixe crescer por 30 minutos.', 4);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Abra os discos, fure a massa com um garfo e pincele o molho.', 5);
INSERT INTO RECEITAS_ETAPAS (ID, RECEITA_ID, DESCRICAO, SEQ) VALUES (DEFAULT, 2, 'Leve ao forno médio (180° C), preaquecido, por 15 minutos.', 6);