INSERT INTO USUARIOS (NOME, SENHA, EMAIL, ID) VALUES ('Felipe de Almeida Gomes', '123', 'falmeidagomes13@gmail.com', DEFAULT);
INSERT INTO USUARIOS (NOME, SENHA, EMAIL, ID) VALUES ('Ketlin Pecharka Nunes', '321', 'kpecharka@gmail.com', DEFAULT);

INSERT INTO CATEGORIAS (DESCRICAO, ID) VALUES ('Doce', DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, ID) VALUES ('Salgado', DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, ID) VALUES ('Delícia', DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, ID) VALUES ('Dia-a-dia', DEFAULT);
INSERT INTO CATEGORIAS (DESCRICAO, ID) VALUES ('Picante', DEFAULT);

INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Leite', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Óleo', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Sal', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Polvilho Doce', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Queijo Ralado', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Ovo', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Açucar', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Milho', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Ervilha', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Azeite', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Farinha de Trigo', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Fermento Biológico', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Água', DEFAULT);
INSERT INTO INGREDIENTES (DESCRICAO, ID) VALUES ('Pinga', DEFAULT);

INSERT INTO RECEITAS (PREPARACAO_MINUTO, ID, USUARIO_ID, OBS_LIVRE, DESCRICAO) VALUES (25, DEFAULT, 1, 'A clássica receita de pão de queijo com polvilho doce amada pelos brasileiros! Descubra como fazer aquela massa fofinha e arrase no preparo do seu pão de queijo caseiro!', 'Pão de Queijo');

INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (2, 1);
INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (3, 1);

INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (1, 1, '2 copos americanos de leite');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (13, 1, '1 copo americano de água');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (2, 1, '1/3 de copo americano de óleo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (3, 1, '1 colher de sopa de sal');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (4, 1, '500 g de polvilho doce');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (5, 1, 'Queijo ralado a gosto');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (6, 1, '3 ovos inteiros');

INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (1, 1, 'Ferva o leite com a água e o óleo.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (2, 1, 'Em uma vasilha misture o polvilho e o sal.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (3, 1, 'Jogue o liquido fervido e misture com uma colher grande.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (4, 1, 'Espere esfriar e despeje o queijo ralado e os ovos.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (5, 1, 'Misture a massa com a mão amassando bem até virar uma cola caseira dura.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (6, 1, 'Faça bolinhas do tamanho que preferir.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (7, 1, 'Asse em forno bem quente até dourar.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (8, 1, 'Sirva quentinho.');


INSERT INTO RECEITAS (PREPARACAO_MINUTO, ID, USUARIO_ID, OBS_LIVRE, DESCRICAO) VALUES (15, DEFAULT, 1, 'Delicinha de pizza', 'Massa de pizza');

INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (2, 2);
INSERT INTO RECEITAS_CATEGORIAS (CATEGORIA_ID, RECEITA_ID) VALUES (4, 2);

INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (11, 2, '1 kg de farinha de trigo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (12, 2, '30 g de fermento biológico');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (13, 2, '3 xícaras de água morna');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (2, 2, '3/4 xícaras de óleo');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (3, 2, '1 colher (chá) de sal');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (7, 2, '1 colher (chá) de açúcar');
INSERT INTO RECEITAS_INGREDIENTES (INGREDIENTE_ID, RECEITA_ID, DESCRICAO) VALUES (14, 2, '1 colher (sopa) de pinga');

INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (1, 2, 'Misture o fermento, o sal e o açúcar em um pouco de água morna, até que o fermento esteja completamente dissolvido.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (2, 2, 'Em seguida, adicione metade da medida de farinha de trigo, o óleo e mexa até criar uma consistência pastosa.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (3, 2, 'Acrescente o restante da farinha de trigo, a pinga, a água morna e misture bem.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (4, 2, 'Assim que a massa desgrudar das mãos, deixe crescer por 30 minutos.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (5, 2, 'Abra os discos, fure a massa com um garfo e pincele o molho.');
INSERT INTO RECEITAS_ETAPAS (SEQ, RECEITA_ID, DESCRICAO) VALUES (6, 2, 'Leve ao forno médio (180° C), preaquecido, por 15 minutos.');